# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bySquareTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bySquareTest

  pod 'LzmaSDK-ObjC', :inhibit_warnings => true
  pod 'LZCompression'

end
